osx_image: xcode10.1
language: objective-c
xcode_sdk: iphonesimulator12.1

xcode_project: ESTabBarControllerExample/ESTabBarControllerExample.xcodeproj
xcode_scheme: ESTabBarControllerExample

# whitelist
branches:
only:
- master